[workspace]

members = [
    "w00_fish",
    "w02_examiner",
    "w03_screenpin",
    "w04_jewelrotator",
    "w05_clientside_focam",
    "w06_ui_reader",
    "w07_ui_healthbar",
    "w08_impulse_player",
    "w09_player_focam",
    "w10_skatemouse",
]