[ember]
id = "w_05_focustarget"
name = "w05_focustarget"
version = "0.0.1"

# input messages
[messages.clear_focus_target.fields]
clear = { type = "Bool" }
[messages.set_focus_target.fields]
focus_target = { type = "EntityId" }

[components]
focuser = { type = "Bool" }
focuser_focus_target = { type = "EntityId" } # add/remove as necessary.
is_focusable = { type = "Bool" } # unused?
is_focused = { type = "Bool" }