[ember]
id = "w_10_skatemouse"
name = "w10_skatemouse"
version = "0.0.1"

[messages.mouse_u_v_zero.fields]
uvzero = { type = "Vec2" }

[messages.mouse_down.fields]
mouse_ray_origin = { type = "Vec3" }
mouse_ray_dir = { type = "Vec3" }

[messages.add_cargo_to_glider.fields]
glider = { type = "EntityId" }

[messages.remove_cargo_from_glider.fields]
glider = { type = "EntityId" }

[components]
local_forward = { type = "Vec3", attributes = ["Networked"] }

plr_glider = { type = "EntityId" }
plr_glidercam = { type = "EntityId", attributes = ["Networked", "Debuggable"] }
is_glider = { type = "Empty", attributes = ["Networked", "Debuggable"] }
is_glidercam = { type = "Empty" }
is_local_player_camera = { type = "Empty" }

glider_desired_landvel = { type = "Vec2", attributes = ["Networked"] }
glider_landvel = { type = "Vec2", attributes = ["Networked"] }
# glider_hook_model = { type = "EntityId" }
glider_hook_pos = { type = "Vec3", attributes = ["Networked"] }
glider_cargo = { type = "EntityId", attributes = ["Networked"] }

glider_stat_max_speed = { type = "F32" }
glider_stat_handling = { type = "F32" }
glider_stat_reverse_speed = { type = "F32" }

proximity_trigger = { type = "F32", attributes = ["Networked", "Debuggable"] }
prox_is_pickup = { type = "Empty" }
prox_is_dropoff = { type = "Empty" }

is_hook_model = { type = "Empty" }
hook_model_pos = { type = "Vec3" }
hook_model_recency = { type = "F32" }

selfie_stick = { type = "Vec3" }
selfie_focus_ent = { type = "EntityId" }
selfie_pitch = { type = "F32" }
selfie_yaw = { type = "F32" }

# player_tracked = { type = "Empty" }
# player_glider = { type = "Empty" }
# glider_vel2 = { type = "Vec2" }
# glider_target = { type = "EntityId" }

# [messages.player_input.fields]
# screen_uv = { type = "Vec2" }
# ray_origin = { type = "Vec3" }
# ray_dir = { type = "Vec3" }
# lmb_held = { type = "Bool" }

# clientside components?
glider_animodel = { type = "EntityId" }
animodel_lookdir = { type = "Vec3", attributes=["Debuggable"] }
animodel_yaw = { type = "F32" }
animodel_yawvel = { type = "F32" }

# is_matter = { type = "Empty" }
matter_gravity = { type = "F32" }
matter_local_center = { type = "Vec3" }

# matter_is_buoyant = { type = "Empty" }
buoy_radius = { type = "F32" }
buoy_submerged = { type = "F32", attributes = ["Debuggable", "Networked"] }
buoy_submerged_center = { type = "Vec3" }
buoy_water_level = { type = "F32" }
buoy_max_force = { type = "F32" }
buoy_max_friction = { type = "F32" }
