[ember]
id = "w_10_skatemouse"
name = "w10_skatemouse"
version = "0.0.1"

[messages.mouse_u_v_zero.fields]
uvzero = { type = "Vec2" }

[messages.mouse_down.fields]
mouse_ray_origin = { type = "Vec3" }
mouse_ray_dir = { type = "Vec3" }

[components]
plr_glider = { type = "EntityId" }
plr_glidercam = { type = "EntityId", attributes = ["Networked", "Debuggable"] }
is_glider = { type = "Empty", attributes = ["Networked", "Debuggable"] }
is_glidercam = { type = "Empty" }
is_local_player_camera = { type = "Empty" }

glider_desired_landvel = { type = "Vec2", attributes = ["Networked"] }
glider_landvel = { type = "Vec2", attributes = ["Networked"] }
# glider_hook_model = { type = "EntityId" }
glider_hook_pos = { type = "Vec3", attributes = ["Networked"] }

is_hook_model = { type = "Empty" }
hook_model_pos = { type = "Vec3" }
hook_model_recency = { type = "F32" }

selfie_stick = { type = "Vec3" }
selfie_focus_ent = { type = "EntityId" }
selfie_pitch = { type = "F32" }
selfie_yaw = { type = "F32" }

# player_tracked = { type = "Empty" }
# player_glider = { type = "Empty" }
# glider_vel2 = { type = "Vec2" }
# glider_target = { type = "EntityId" }

# [messages.player_input.fields]
# screen_uv = { type = "Vec2" }
# ray_origin = { type = "Vec3" }
# ray_dir = { type = "Vec3" }
# lmb_held = { type = "Bool" }

# clientside components?
glider_animodel = { type = "EntityId" }
animodel_lookdir = { type = "Vec3", attributes=["Debuggable"] }
animodel_yaw = { type = "F32" }
animodel_yawvel = { type = "F32" }
